/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
Toolkit.getDefaultToolkit().getImage(Login.class.getResource("/src_images/QPDLogo.png"))
 */
package signup;
//import mainwindow.mainWindow;
//import java.awt.Toolkit;
import files.DatabaseConnect;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import files.createDirectory;
/**
 *
 * @author PC-9
 */
public class Login extends javax.swing.JFrame {

    /** * Creates new form Login
     */
    public Login() {
        initComponents();
        createDirectory.create();
    }
    public void testlogin(){
            // TODO:
        //fetch data then throw to database for comparison
        //if not match, thow error message to error_message_text_label
        //System.out.println("Mouse Click");
        String username = username_field.getText();
        //String password = password_field.getPassword();
        String password = new String(password_field.getPassword());
        if(username.equals("")){
            error_message_text.setText("*Username is required");
            username_field.requestFocusInWindow();
        }
        else if(password.equals("")){
            error_message_text.setText("*Password is required");
            password_field.requestFocusInWindow();
        }
        else{
            //throw me to database else error message
            String col ="privilege";
            //String query = "SELECT "+col+" FROM TBL_ACCOUNT WHERE username like "+username+"";
            String query;
            query = "SELECT "+col+" FROM TBL_ACCOUNT where username like '"+username+"' and password like '"+password+"'";
            DatabaseConnect.connect();
            String value=(DatabaseConnect.getValue(query,col));
            if(value==""){
                error_message_text.setText("*Wrong Email or Password");
                username_field.requestFocusInWindow();
            }
            else{
                this.setVisible(false);
                //new mainwindow.mainWindow().setVisible(true);
                //fetch username
                //fetch value
                if("CASHIER".equals(value)){
                                            //call the neccesary funtion and pass a value
                                            new cashier.transOption(username).setVisible(true);
                                            this.dispose();
                                            }
                else{
                     JOptionPane.showMessageDialog(null, "Module not yet created","Just a messege",3);
                }
            }
        }                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password_label = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        error_message_text = new javax.swing.JLabel();
        Login_Button = new javax.swing.JButton();
        forget_pass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Signin_text = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QuestPhil Diagnostics");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        password_label.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        password_label.setText("Password: ");

        username_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                username_fieldKeyReleased(evt);
            }
        });

        password_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                password_fieldKeyReleased(evt);
            }
        });

        error_message_text.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        error_message_text.setForeground(new java.awt.Color(204, 0, 0));
        error_message_text.setText(" ");
        error_message_text.setMaximumSize(new java.awt.Dimension(5, 25));
        error_message_text.setMinimumSize(new java.awt.Dimension(5, 25));
        error_message_text.setPreferredSize(new java.awt.Dimension(5, 25));

        Login_Button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Login_Button.setText("Log In");
        Login_Button.setPreferredSize(new java.awt.Dimension(73, 34));
        Login_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Login_ButtonMouseReleased(evt);
            }
        });
        Login_Button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Login_ButtonKeyReleased(evt);
            }
        });

        forget_pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        forget_pass.setForeground(new java.awt.Color(51, 102, 255));
        forget_pass.setText("Forget Password?");
        forget_pass.setToolTipText("Get your recovery code here");
        forget_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forget_passMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src_images/QPD.png"))); // NOI18N

        Signin_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Signin_text.setForeground(new java.awt.Color(51, 102, 255));
        Signin_text.setText("Sign In.");

        username_label.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        username_label.setText("Username:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src_images/gear.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Signin_text, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(username_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(password_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(password_field))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(error_message_text, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 15, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(forget_pass)
                        .addGap(18, 18, 18)
                        .addComponent(Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Signin_text)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(error_message_text, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forget_pass))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Login");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void forget_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forget_passMouseClicked
        // TODO:
        //redirect me to new dialog for email input password recovery then close this page
        //System.out.println("Forget password is being pressed");
        if(evt.getButton()== MouseEvent.BUTTON1){  
        this.dispose();
        new forgetpassword().setVisible(true);
        }
    }//GEN-LAST:event_forget_passMouseClicked

    private void username_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_fieldKeyReleased
        // TODO: delete comment
          error_message_text.setText("");
    }//GEN-LAST:event_username_fieldKeyReleased

    private void password_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_fieldKeyReleased
        // TODO: delete comment
           error_message_text.setText("");
    }//GEN-LAST:event_password_fieldKeyReleased

    private void Login_ButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_ButtonMouseReleased
        // TODO add your handling code here:
                if(evt.getButton()== MouseEvent.BUTTON1){testlogin();}  
    }//GEN-LAST:event_Login_ButtonMouseReleased

    private void Login_ButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Login_ButtonKeyReleased
        // TODO add your handling code here:
               if(evt.getKeyCode() == KeyEvent.VK_ENTER){testlogin();}
    }//GEN-LAST:event_Login_ButtonKeyReleased

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
       new settings.ipsetup().setVisible(true);
       this.setVisible(false);   
    }//GEN-LAST:event_jButton1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_Button;
    private javax.swing.JLabel Signin_text;
    private javax.swing.JLabel error_message_text;
    private javax.swing.JLabel forget_pass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField username_field;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
